modLoader = "javafml" 
loaderVersion = "${neoforge_loader_version_range}" 
license = "${license}" 
issueTrackerURL="https://github.com/lpsmods/spawner-craft/issues"

[[mods]] 
modId = "${mod_id}" 
version = "${version}" 
displayName = "${mod_name}"
updateJSONURL="https://api.modrinth.com/updates/spawner-craft/forge_updates.json"
displayURL="https://lpsmods.dev/" 
logoFile="${mod_id}.png" 
credits="${credits}" 
authors = "${mod_author}" 
description = '''${description}''' 
[[dependencies.${mod_id}]] 
modId = "neoforge" 
type="required" 
versionRange = "[${neoforge_version},)" 
ordering = "NONE" 
side = "BOTH" 
[[dependencies.${mod_id}]]
modId = "minecraft"
type="required" 
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
